import Image from "next/image";
import styles from "../globals.css";
import MyLink from "../components/MyLink";

export default function Home() {
  return (
<div classname="ecdiv">
<h1>Why the Electoral College Should be Removed</h1>
<h2>What is the Electoral College?</h2>
<p>The Electoral College is the U.S.'s system for the presidential election. Each state gets a number out of 538 votes based on its population and the candidate who gets 270 votes or more, wins. Those numbers can change from year to year. People vote a couple of days before. Then, on the first Tuesday after the first Monday of November, election day takes place. This is when they announce the votes tallied up by the machines. People can still vote on that day. Youâ€™re thinking, the person who gets the most electoral votes surely has to be the person with the most popular votes? Well, no. The person who gets the popular vote doesnâ€™t always win the election. For example, if 6,000,000 million people in California voted for Thomas Jefferson and 6,000,001 people voted for James Monroe, James Monroe would take all 54 votes. That is because of the rule that the winner takes all. Read on to learn about the 2000 Presidential Election and the 2016 Presidential Election, two of the five times when the popular vote lost.</p>
<h2>The 2000 Presidential Election</h2>
<p>For the 4th time in history and the first time since 1888, the person with the popular vote lost. In the year 2000, the two candidates running were George Walker Bush (Republican), son of the 41st President, George Herbert Walker, and Albert Gore (Democrat), the current Vice President of the time. A third candidate was Pat Buchanan from the Reform Party. More about his role will come later. Okay, now the candidates nominated their running mates a couple of months before the election. Al Gore chose Senator Joe Liberman and George Bush chose Dick Cheney from the United States Secretary of Defense during his fatherâ€™s adminastrion. On November 7th, Bush had 256 electoral votes and Gore had 266 electoral votes. The last state to be counted was Florida, which had 25 votes. News channels first predicted that Gore would win, but then they said that Bush would win with a lead too high too overcome. The results of the election were too close. Bush had a slight lead of only 600 votes. Florida state election law required a recount. On November 10th, they finished. Bushâ€™s lead shrunk from 600 to now 327 votes. They now were going to do a manual recount. They started doing it and after a while and many court cases, they never finished the recount. George W. Bush said it was breaking the 14th Amendment of the Constitution. So, the result of the 2000 Flordia State Election was that Bush had won by less than a tenth of a percent. The popular votes on the otherhand were different. Bush got 50,455,156 votes, while Al Gore got 50,992,335 votes, almost 500,000 more votes. So, that is how George W. Bush became our 43rd President.</p>
<h2>The 2016 Election</h2>
<p>The 2016 election was the 58th election. The two main candidates and their vice president nominees were Hillary Clinton and Tim Kaine from the Democratic Party and Donald Trump and Mike Pence from the Republican Party. Donald Trump was one of the few presidents that had never had any other political experience. Hilary Clinton was the First Lady of the United States from 1993 - 2000 during Clintonâ€™s term. She was secretary of state after she lost the 2008 Democratic Party election against Barack Obama. In the 2016 election, Donald Trump received 62,984,828 votes and Hillary Clinton received 65,853,514 votes. This means Hillary Clinton won, right? No. Remember the Electoral College? Trump received 304 Electoral Votes, while Clinton only received 227 Electoral Votes. So, this meant the Donald Trump had won the election, even after losing the popular vote. He was the 5th president to win in that way.</p>

<h2>Why It Should Be Removed</h2>
<p>The Electoral College should be abolished because it is an unfair system and and is unfavored. The Electoral College is unfair because giving a state a number of votes based on the population doesnâ€™t make sense. For example, if California had 1,000 people and received 10 Electoral Votes and New York has 999 people, and received 9 electoral votes, it is not proportional. If the Democratic Party got 1,000 popular votes, 499 from California and 875 from New York and the Republican Party got 501 votes from California and 124 votes from New York, the Republican Party would get 10 Electoral Votes, while the Democratic Party would only get 9. So, even if the person with more popular votes, they donâ€™t win because of the unfair system created by the founding fathers. An article from Harvard Politics states, â€œThe Electoral Collegeâ€™s winner-take-all system has long been criticized for allowing candidates to focus on a few â€œswing statesâ€ while ignoring the rest of the country. In 2020, for example, six million Californians voted for former President Trump, the most votes a Republican has ever received in any state in any race since the countryâ€™s founding. Yet, all 55 of Californiaâ€™s electoral votes went to Joe Biden, a crucial element of his victory. Similar phenomena happen in nearly every â€œsafe stateâ€; only Nebraska and Maine have attempted to create more proportional systems by dividing their electoral votes by congressional district,â€(Agarwal). This means that the 6 million people who voted for Donald Trump didnâ€™t get a say in the presidency. This meant it was unfair. The Electoral College is also highly unfavored. According to Pewresearch.org, â€œNearly two-thirds of U.S. adults (65%) say the way the president is elected should be changed so that the winner of the popular vote nationwide wins the presidency. A third favor keeping the current Electoral College system,â€(Kiley). This means that most people donâ€™t like it and we should get rid of it. Also, we should use the popular vote to choose the president. Also, Gallup News says, â€œHeading into the 2020 presidential election, three in five Americans favor amending the U.S. Constitution to replace the Electoral College with a popular vote system,...â€(Brenan). This also means that most people do not like it. This is why it should be abolished. So now, what do you think? Should we keep the Electoral College or should we switch to the popular vote?</p>
</div>

  );
};